server:
  port: 8084

spring:
  application:
    name: betting-service

  datasource:
    url: jdbc:postgresql://localhost:5432/betfut_bets_db
    username: postgres
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/