server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1

            - id: match-service
              uri: lb://MATCH-SERVICE
              predicates:
                - Path=/api/matches/**
              filters:
                - StripPrefix=1

            - id: wallet-service
              uri: lb://WALLET-SERVICE
              predicates:
                - Path=/api/wallets/**
              filters:
                - StripPrefix=1

            - id: betting-service
              uri: lb://BETTING-SERVICE
              predicates:
                - Path=/api/bets/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/